### PR TITLE
added ability to have css underline

### PR DESCRIPTION
**Pull request by MarkNijhof**
Look at: http://creativeit.github.io/getmdl-select/ for an example, or just run the code, the Example1 has changed to include this

### CODE REVIEW

**Comment by MarkNijhof** [comment]
Btw to explain the change, I needed a div that is a direct sibling of the input box so I can use the ~ CSS selector to trigger changes when input gets or loses focus, you can see the CSS in the example index.html file. I wanted to do this using CSS as it works great and avoids using Elm (js). This is the Material UI style in case you were wondering. 

Please advise if this is a change you are willing to accept so I know if I should spend time on a different solution :-)

**Comment by sporto** [comment]
There is a `inputWrapperClass`. Is this something that could be achieved using that?

**Comment by MarkNijhof** [comment]
I don't think so as the wrapper is the parent and that cannot be selected using CSS. It needs to be a node at the same level as the node that gets the focus. If I want to do this else where in the dom tree then I need to use JS.

http://stackoverflow.com/questions/10782054/what-does-the-tilde-squiggle-twiddle-css-selector-mean

**Comment by MarkNijhof** [comment]
This PR has been open now for a while, any input?

Should I release my own fork for this functionality (I really need it and I haven't found a way around it otherwise). I also really don't like publishing a fork though :-)

**Comment by sporto** [comment]
Sorry, I haven't come up with any alternative. I will merge this.

**Comment by sporto** [comment]
Published 2.6

**Comment by MarkNijhof** [comment]
Thanks :100:

**Pull request merged**
