### PR TITLE
added fuzzy config options

### PR DESCRIPTION
**Pull request by MarkNijhof**

### CODE REVIEW

**Comment by MarkNijhof** [comment]
We are using elm-select with 20k items and we need to fine tune the fuzzy search a bit. So I added a few withXyz functions that allow you to do so.

**Comment by MarkNijhof** [comment]
Btw the reason for the add/remove/move functions is because Fuzzy doesn't expose Config only the three functions that modify it

**Comment by sporto** [comment]
Nice thanks

**Comment by MarkNijhof** [comment]
Cool! Will you make a release so we can use it properly?

**Comment by sporto** [comment]
Published 2.5.0

**Comment by MarkNijhof** [comment]
Thanks

**Pull request merged**
